{{- if eq .Values.app.namespace "ff61fb-prod" }}
apiVersion: v1
kind: Secret
metadata:
  name: ccbc-test-db-secret
  labels:
{{ include "ccbc.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  test-password: {{ .Values.db.test.password | default "" | b64enc | quote }}
{{- end }}
