# We may have to remove this and use crunchy minAvailable once the operator is upgraded
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pg-bouncer-pdb
  labels: {{ include "ccbc.labels" . | nindent 4 }}
spec:
  minAvailable: {{ sub .Values.pgBouncer.replicas 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ template "ccbc.fullname" . }}
      postgres-operator.crunchydata.com/role: pgbouncer

